repos:
  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: flake8
        exclude: misc
        additional_dependencies: [
          'flake8==3.7.7',
          'flake8-builtins==1.4.1',
          'flake8-bugbear==19.3.0',
        ]
  - repo: https://github.com/pycqa/bandit
    rev: 1.6.0
    hooks:
      - id: bandit
        args: [-lll]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.701
    hooks:
      - id: mypy
        # mypy v0.701 fails to build on python3.8 https://github.com/python/typed_ast/issues/124
        # FIXME: remove language version with mypy v0.761
        language_version: python3.7
